language: java

jdk:
 - oraclejdk8

# Run on container-based infrastructure
sudo: false

cache:
  directories:
    - ${HOME}/.m2/repository

install:
  - mvn --show-version dependency:resolve

script:
  - mvn --batch-mode test

deploy:
  # Only deploy on successful merge into master
  - ([[ ${TRAVIS_BRANCH} == "master" && ${TRAVIS_PULL_REQUEST} == false ]] && mvn --batch-mode deploy -DskipTests)
